### ISSUE TITLE
Problem running docker images

### ISSUE THREAD

**Issue by ConstantB** [frmichel/sparql-micro-service#1]
Hello, 

I try to run the docker image but I  encountered the following issues: 

First, I tried to follow the instructions and run docker-compose up -d in the directory the .yml file is located (after cloning this repo) but I got the following error:  
` build path .../sparql-micro-service/docker/sms-corese either does not exist, is not accessible, or is not a valid URL
`
Then, since I only want the sparql-micro-service docker, I downloaded this docker using docker pull and ran this command: 

> docker run -i -t  frmichel/sparql-micro-service

Although I the docker instance seemed to be running, I could not access it via localhost:81. I noticed that it was running using port 80 instead of 81. So I added the port mapping to my command: 

> docker run -i -t -p 81:80   frmichel/sparql-micro-service

After typing localhost:81 on the browser this time I noticed that the port 81 is now used by the docker but I get an access forbidden message. More specifically, I get the following error in the docker logs: 

`Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

Is there something I am missing? Do I have to perform any other configurations? 

Any help would be very much appreciated! 

Best, 

Constantina

**Comment by frmichel** [comment]
Pasting here the response sent by email on Oct. 19th 2018.

---
Dear Konstantina,

I found the problem: I committed the docker compose file that I use to build to images. To run it, simply remove those two lines starting with "build" and retry. I have updated the github repository accordingly, on the main branch.

Also, as documented,
- don't forget to set rights 777 on directory logs, and
- use localhost:81 to call the services, e.g.:

```curl --header "Accept: application/sparql-results+json" "http://localhost:81/sparqlms/musicbrainz/getSongByName?query=select%20*%20where%20%7B%3Fs%20%3Fp%20%3Fo%7D&name=Delphinus+delphis"```

Regards,
   Franck.
