### ISSUE TITLE
discussion: a similar project

### ISSUE THREAD

**Issue by justin2004** [frmichel/sparql-micro-service#18]
hi @frmichel 
i just came across your project and noticed how similar it is to
https://github.com/SPARQL-Anything/sparql.anything.

e.g. look how i use SPARQL Anything to write SPARQL queries against the arXiv REST API:
https://github.com/justin2004/weblog/tree/master/dynamic_pagination_with_sparql_anything

i wonder if we want to think about working together?

**Comment by frmichel** [comment]
Dear @justin2004, shame on me for waiting such a long time before answering.
 I'm so sorry about that.

I've known about SPARQL-Anything in particular when we, at the KG construction W3C WG, had a presentation by someone from your team. Indeed there are definitely commonalities between this project and SPARQL micro-services.

> i wonder if we want to think about working together?

I'm definitely open to collaborations, suggestions etc. Do you have something precise mind? Some topic you'd like to address?

Franck.
