### ISSUE TITLE
Nested calls to micro-services don't work

### ISSUE THREAD

**Issue by antoniaettorre** [frmichel/sparql-micro-service#6]
The micro-service does not work if the SPARQL query contains a SERVICE keyword.

**Comment by frmichel** [comment]
Due to a deadlock occurring in the [Corese SPARQL engine](https://github.com/Wimmics/corese/).

Not sure it would work better with other SPARQL engines since they often forbid SERVICE clauses to other domains anyway.

Investigation on-going on Corese side.

**Comment by frmichel** [comment]
Fixed in Corese (4.1.1 snapshot 2019-04-02) + [bug fix](https://github.com/frmichel/sparql-micro-service/commit/e2b19262085d7d24d474dbf820e67e063dfb27e0) in SPARQL micro-services.
